import type { Metadata } from "next";
import Link from "next/link";

import Hero from "@/components/Hero";
import CalculatorCard from "@/components/CalculatorCard";
import FeatureCard from "@/components/FeatureCard";
import UserCard from "@/components/UserCard";

export const metadata: Metadata = {
  title: "BizTools | Free Business Calculators",

  description:
    "Free business calculators for profit, break-even point, pricing, ROI and sales targets. Built for entrepreneurs, freelancers, small businesses and online sellers.",

  keywords: [
    "business calculator",
    "profit calculator",
    "break even calculator",
    "pricing calculator",
    "ROI calculator",
    "sales target calculator",
    "small business tools",
    "entrepreneur tools",
    "freelance calculator",
  ],

  alternates: {
    canonical: "/en",

    languages: {
      "ja-JP": "/",
      "en-US": "/en",
      "x-default": "/",
    },
  },

  openGraph: {
    title: "BizTools | Free Business Calculators",

    description:
      "Calculate profit, break-even point, pricing, ROI and sales targets with free business calculators.",

    url: "/en",

    siteName: "BizTools",

    locale: "en_US",

    type: "website",
  },

  twitter: {
    card: "summary_large_image",

    title: "BizTools | Free Business Calculators",

    description:
      "Free calculators for profit, pricing, break-even analysis, ROI and sales targets.",
  },

  robots: {
    index: true,
    follow: true,
  },
};

export default function Home() {
  return (
    <main
      style={{
        maxWidth: "1100px",
        margin: "0 auto",
        padding: "0 24px 100px",
      }}
    >
      <Hero lang="en" />

      {/* Popular Business Tools */}

      <section
        style={{
          marginTop: "40px",
        }}
      >
        <h2
          style={{
            fontSize: "40px",
            fontWeight: 700,
            textAlign: "center",
            color: "#111827",
          }}
        >
          Popular Business Tools
        </h2>

        <p
          style={{
            marginTop: "18px",
            textAlign: "center",
            maxWidth: "760px",
            marginInline: "auto",
            color: "#6B7280",
            lineHeight: 1.8,
            fontSize: "18px",
          }}
        >
          BizTools provides free business calculators for entrepreneurs,
          freelancers, small business owners and online sellers who need
          quick answers to important financial questions.
        </p>

        <p
          style={{
            marginTop: "14px",
            textAlign: "center",
            maxWidth: "760px",
            marginInline: "auto",
            color: "#6B7280",
            lineHeight: 1.8,
            fontSize: "17px",
          }}
        >
          Check whether your business is profitable, find a suitable selling
          price, calculate how many units you need to sell and evaluate the
          return generated by an investment.
        </p>

        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(auto-fit,minmax(300px,1fr))",
            gap: "28px",
            marginTop: "50px",
          }}
        >
          <CalculatorCard
            icon="📈"
            title="Profit Calculator"
            description="Use revenue, variable costs and fixed costs to calculate profit, profit margin and contribution."
            bestFor={`• Small Business
• Freelancers
• Online Sellers`}
            href="/en/profit-calculator"
            popular
            lang="en"
          />

          <CalculatorCard
            icon="⚖️"
            title="Break-even Calculator"
            description="Calculate the sales volume and revenue required to cover your fixed and variable costs."
            bestFor={`• Startups
• Retail
• Restaurants`}
            href="/en/break-even-calculator"
            lang="en"
          />

          <CalculatorCard
            icon="🎯"
            title="Sales Target Calculator"
            description="Calculate the units and revenue required to reach a specific profit target."
            bestFor={`• Business Planning
• Forecasting`}
            href="/en/sales-target-calculator"
            lang="en"
          />

          <CalculatorCard
            icon="💰"
            title="Pricing Calculator"
            description="Use your product cost and desired margin to calculate a target selling price."
            bestFor={`• Products
• Services
• Ecommerce`}
            href="/en/pricing-calculator"
            lang="en"
          />

          <CalculatorCard
            icon="📊"
            title="ROI Calculator"
            description="Measure return on investment, net profit and investment multiple."
            bestFor={`• Marketing
• Equipment
• Projects`}
            href="/en/roi-calculator"
            lang="en"
          />
        </div>
      </section>

      {/* What You Can Calculate */}

      <section
        style={{
          marginTop: "100px",
          padding: "50px",
          background: "#F9FAFB",
          border: "1px solid #E5E7EB",
          borderRadius: "24px",
        }}
      >
        <h2
          style={{
            margin: 0,
            fontSize: "36px",
            fontWeight: 800,
            color: "#111827",
            textAlign: "center",
          }}
        >
          What Can You Calculate with BizTools?
        </h2>

        <p
          style={{
            marginTop: "20px",
            maxWidth: "780px",
            marginInline: "auto",
            fontSize: "17px",
            lineHeight: 1.9,
            color: "#4B5563",
            textAlign: "center",
          }}
        >
          Revenue alone does not tell you whether a business is performing
          well. Profitability also depends on costs, pricing, sales volume and
          how efficiently money is invested. BizTools helps you examine these
          numbers separately and use them together.
        </p>

        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(auto-fit,minmax(230px,1fr))",
            gap: "22px",
            marginTop: "40px",
          }}
        >
          {[
            {
              title: "Measure Profit",
              text:
                "Subtract variable and fixed costs from revenue to understand how much profit the business is actually producing.",
            },
            {
              title: "Find Break-even",
              text:
                "Calculate the minimum sales volume required to cover your costs before the business begins generating profit.",
            },
            {
              title: "Evaluate Pricing",
              text:
                "Use product cost and your desired margin to estimate a selling price that supports your profitability goals.",
            },
            {
              title: "Measure Investment Return",
              text:
                "Evaluate how effectively spending on marketing, equipment or other projects generates a financial return.",
            },
          ].map((item) => (
            <div
              key={item.title}
              style={{
                background: "#FFFFFF",
                border: "1px solid #E5E7EB",
                borderRadius: "16px",
                padding: "26px",
              }}
            >
              <h3
                style={{
                  margin: 0,
                  fontSize: "20px",
                  fontWeight: 700,
                  color: "#111827",
                }}
              >
                {item.title}
              </h3>

              <p
                style={{
                  marginTop: "12px",
                  marginBottom: 0,
                  lineHeight: 1.8,
                  color: "#6B7280",
                }}
              >
                {item.text}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Business Calculation Workflow */}

      <section
        style={{
          marginTop: "100px",
        }}
      >
        <h2
          style={{
            fontSize: "40px",
            fontWeight: 700,
            textAlign: "center",
            color: "#111827",
          }}
        >
          A Simple Business Calculation Workflow
        </h2>

        <p
          style={{
            marginTop: "18px",
            maxWidth: "780px",
            marginInline: "auto",
            textAlign: "center",
            fontSize: "18px",
            lineHeight: 1.8,
            color: "#6B7280",
          }}
        >
          Each calculator can be used independently, but combining the
          results can give you a clearer picture of your business model.
        </p>

        <div
          style={{
            display: "grid",
            gap: "20px",
            marginTop: "45px",
          }}
        >
          {[
            {
              number: "1",
              title: "Understand Cost and Pricing",
              text:
                "Start with the cost of your product or service. Use the Pricing Calculator to see what selling price may be required to achieve your desired margin.",
              href: "/en/pricing-calculator",
              linkText: "Open Pricing Calculator",
            },
            {
              number: "2",
              title: "Calculate Your Break-even Point",
              text:
                "Once price and costs are known, calculate how many units must be sold before your fixed costs are fully covered.",
              href: "/en/break-even-calculator",
              linkText: "Calculate Break-even",
            },
            {
              number: "3",
              title: "Set a Sales Target",
              text:
                "Add a desired profit target and calculate the sales volume and revenue required to reach that goal.",
              href: "/en/sales-target-calculator",
              linkText: "Calculate Sales Target",
            },
            {
              number: "4",
              title: "Review Profit and Investment Performance",
              text:
                "Compare actual revenue and expenses with your plan, then evaluate whether investments such as advertising or equipment produced an adequate return.",
              href: "/en/roi-calculator",
              linkText: "Calculate ROI",
            },
          ].map((item) => (
            <div
              key={item.number}
              style={{
                display: "grid",
                gridTemplateColumns: "60px 1fr",
                gap: "22px",
                alignItems: "start",
                padding: "28px",
                border: "1px solid #E5E7EB",
                borderRadius: "18px",
                background: "#FFFFFF",
              }}
            >
              <div
                style={{
                  width: "52px",
                  height: "52px",
                  borderRadius: "50%",
                  background: "#2563EB",
                  color: "#FFFFFF",
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  fontWeight: 800,
                  fontSize: "20px",
                }}
              >
                {item.number}
              </div>

              <div>
                <h3
                  style={{
                    margin: 0,
                    fontSize: "22px",
                    fontWeight: 700,
                    color: "#111827",
                  }}
                >
                  {item.title}
                </h3>

                <p
                  style={{
                    marginTop: "10px",
                    marginBottom: 0,
                    lineHeight: 1.8,
                    color: "#4B5563",
                  }}
                >
                  {item.text}
                </p>

                <Link
                  href={item.href}
                  style={{
                    display: "inline-block",
                    marginTop: "14px",
                    color: "#2563EB",
                    fontWeight: 700,
                    textDecoration: "none",
                  }}
                >
                  {item.linkText} →
                </Link>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Example */}

      <section
        style={{
          marginTop: "100px",
        }}
      >
        <h2
          style={{
            fontSize: "40px",
            fontWeight: 700,
            textAlign: "center",
            color: "#111827",
          }}
        >
          Example: Planning a Product Business
        </h2>

        <p
          style={{
            marginTop: "18px",
            maxWidth: "780px",
            marginInline: "auto",
            textAlign: "center",
            color: "#6B7280",
            lineHeight: 1.8,
            fontSize: "18px",
          }}
        >
          Imagine that you sell a product for $30. Looking only at revenue
          does not tell you whether the product is actually profitable.
        </p>

        <div
          style={{
            marginTop: "40px",
            padding: "36px",
            border: "1px solid #E5E7EB",
            borderRadius: "20px",
            background: "#F9FAFB",
          }}
        >
          <p
            style={{
              margin: 0,
              fontSize: "17px",
              lineHeight: 1.9,
              color: "#374151",
            }}
          >
            Suppose the selling price is $30, variable cost is $12 per unit
            and monthly fixed costs are $1,800. Each unit contributes $18
            toward fixed costs and profit. A break-even calculation can then
            show how many units must be sold before the $1,800 in fixed costs
            has been recovered.
          </p>

          <p
            style={{
              marginTop: "18px",
              marginBottom: 0,
              fontSize: "17px",
              lineHeight: 1.9,
              color: "#374151",
            }}
          >
            If you also want to earn $3,000 in monthly profit, the Sales
            Target Calculator can estimate the number of units and amount of
            revenue required. Combining these calculations helps answer three
            practical questions: what price should you charge, how much must
            you sell and how much profit could remain.
          </p>
        </div>
      </section>

      {/* Why BizTools */}

      <section
        style={{
          marginTop: "100px",
        }}
      >
        <h2
          style={{
            fontSize: "40px",
            fontWeight: 700,
            textAlign: "center",
            color: "#111827",
          }}
        >
          Why BizTools?
        </h2>

        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(auto-fit,minmax(240px,1fr))",
            gap: "24px",
            marginTop: "50px",
          }}
        >
          <FeatureCard
            icon="⚡"
            title="Fast & Simple"
            description="Check important business numbers without building complicated spreadsheets."
            href="/en/about"
            lang="en"
          />

          <FeatureCard
            icon="🎯"
            title="Built for Business"
            description="Focused on practical calculations involving profit, pricing, sales and investment."
            href="/en/about"
            lang="en"
          />

          <FeatureCard
            icon="📱"
            title="Works Everywhere"
            description="Use the calculators on desktop, tablet or mobile whenever you need them."
            href="/en/about"
            lang="en"
          />

          <FeatureCard
            icon="✅"
            title="Free to Use"
            description="No account, subscription or payment is required to use the calculators."
            href="/en/about"
            lang="en"
          />
        </div>
      </section>

      {/* Who Uses BizTools */}

      <section
        style={{
          marginTop: "100px",
        }}
      >
        <h2
          style={{
            fontSize: "40px",
            fontWeight: 700,
            textAlign: "center",
            color: "#111827",
          }}
        >
          Who Uses BizTools?
        </h2>

        <p
          style={{
            marginTop: "18px",
            textAlign: "center",
            maxWidth: "700px",
            marginInline: "auto",
            color: "#6B7280",
            lineHeight: 1.8,
            fontSize: "18px",
          }}
        >
          BizTools is designed for people who want to understand business
          numbers without unnecessary complexity.
        </p>

        <div
          style={{
            display: "grid",
            gridTemplateColumns:
              "repeat(auto-fit,minmax(250px,1fr))",
            gap: "24px",
            marginTop: "50px",
          }}
        >
          <UserCard
            icon="🚀"
            title="Entrepreneurs"
            description="Explore pricing, break-even points and sales requirements while evaluating a business idea."
          />

          <UserCard
            icon="💼"
            title="Freelancers"
            description="Evaluate service pricing, required revenue and profitability before accepting or planning work."
          />

          <UserCard
            icon="🏪"
            title="Small Businesses"
            description="Review profit, sales, fixed costs and variable costs to support everyday business decisions."
          />

          <UserCard
            icon="🎓"
            title="Students"
            description="Practice important concepts such as profit margin, break-even analysis and ROI using practical examples."
          />
        </div>
      </section>

      {/* CTA */}

      <section
        style={{
          marginTop: "110px",
          background: "#2563EB",
          borderRadius: "28px",
          padding: "70px 40px",
          textAlign: "center",
        }}
      >
        <h2
          style={{
            fontSize: "42px",
            fontWeight: 800,
            color: "#FFFFFF",
            margin: 0,
          }}
        >
          Make Business Numbers Easier to Understand
        </h2>

        <p
          style={{
            marginTop: "24px",
            fontSize: "20px",
            lineHeight: 1.8,
            color: "#DBEAFE",
            maxWidth: "760px",
            marginInline: "auto",
          }}
        >
          Use our free calculators to check profit, pricing, break-even
          points, ROI and sales targets whenever you need them.
        </p>

        <div
          style={{
            display: "flex",
            justifyContent: "center",
            gap: "20px",
            flexWrap: "wrap",
            marginTop: "40px",
          }}
        >
          <Link
            href="/en/calculators"
            style={{
              background: "#FFFFFF",
              color: "#2563EB",
              textDecoration: "none",
              padding: "16px 34px",
              borderRadius: "12px",
              fontWeight: 700,
              fontSize: "17px",
            }}
          >
            Browse Business Tools →
          </Link>

          <Link
            href="/en/profit-calculator"
            style={{
              border: "2px solid rgba(255,255,255,.4)",
              color: "#FFFFFF",
              textDecoration: "none",
              padding: "16px 34px",
              borderRadius: "12px",
              fontWeight: 700,
              fontSize: "17px",
            }}
          >
            Try Profit Calculator
          </Link>
        </div>
      </section>

      {/* FAQ */}

      <section
        style={{
          marginTop: "110px",
        }}
      >
        <h2
          style={{
            fontSize: "40px",
            fontWeight: 700,
            textAlign: "center",
            color: "#111827",
          }}
        >
          Frequently Asked Questions
        </h2>

        <div
          style={{
            marginTop: "50px",
            display: "grid",
            gap: "24px",
          }}
        >
          {[
            {
              question: "Are the BizTools calculators free?",
              answer:
                "Yes. All business calculators currently available on BizTools can be used free of charge.",
            },
            {
              question: "Do I need to create an account?",
              answer:
                "No. Registration and login are not required. Open a calculator and enter your numbers to use it immediately.",
            },
            {
              question: "Which calculator should I use first?",
              answer:
                "Use the Profit Calculator to review current profitability. If you want to know the minimum sales required to cover your costs, start with the Break-even Calculator.",
            },
            {
              question: "Can I use the results for business planning?",
              answer:
                "The results can be useful as a starting point for planning and comparison. Actual business decisions may also need to consider taxes, market conditions, financing and other expenses.",
            },
            {
              question: "Is BizTools available in Japanese?",
              answer:
                "Yes. BizTools is available in Japanese and English. Japanese pages display monetary values in yen, while English pages display monetary values in U.S. dollars.",
            },
          ].map((item) => (
            <div
              key={item.question}
              style={{
                background: "#FFFFFF",
                border: "1px solid #E5E7EB",
                borderRadius: "18px",
                padding: "28px",
              }}
            >
              <h3
                style={{
                  margin: 0,
                  fontSize: "22px",
                  color: "#111827",
                }}
              >
                {item.question}
              </h3>

              <p
                style={{
                  marginTop: "16px",
                  marginBottom: 0,
                  color: "#6B7280",
                  lineHeight: 1.8,
                }}
              >
                {item.answer}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* About */}

      <section
        style={{
          marginTop: "100px",
          padding: "36px",
          borderTop: "1px solid #E5E7EB",
        }}
      >
        <h2
          style={{
            fontSize: "28px",
            fontWeight: 700,
            color: "#111827",
          }}
        >
          About BizTools
        </h2>

        <p
          style={{
            marginTop: "18px",
            maxWidth: "850px",
            fontSize: "17px",
            lineHeight: 1.9,
            color: "#4B5563",
          }}
        >
          BizTools is a collection of free calculators designed to make
          common business calculations easier to understand. The tools can
          be used for quick checks involving profitability, pricing, sales
          planning and investment performance.
        </p>

        <p
          style={{
            marginTop: "16px",
            fontSize: "16px",
            lineHeight: 1.8,
            color: "#6B7280",
          }}
        >
          Learn more on the{" "}
          <Link
            href="/en/about"
            style={{
              color: "#2563EB",
              fontWeight: 700,
              textDecoration: "none",
            }}
          >
            About BizTools
          </Link>{" "}
          page.
        </p>
      </section>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            name: "BizTools",
            url: "https://uttacca.com/en",
            description:
              "Free business calculators for profit, break-even analysis, pricing, ROI and sales targets.",
            inLanguage: "en-US",
          }),
        }}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: [
              {
                "@type": "Question",
                name: "Are the BizTools calculators free?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text:
                    "Yes. All business calculators currently available on BizTools can be used free of charge.",
                },
              },
              {
                "@type": "Question",
                name: "Do I need to create an account?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text:
                    "No. Registration and login are not required.",
                },
              },
              {
                "@type": "Question",
                name: "Can I use the results for business planning?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text:
                    "The results can be useful as a starting point for planning and comparison, while actual decisions may also need to consider taxes, market conditions and other expenses.",
                },
              },
            ],
          }),
        }}
      />
    </main>
  );
}